# Generated by Django 4.2.7 on 2023-12-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_completed_tasks_userprofile_total_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='completed_tasks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_tasks',
        ),
    ]
