# Generated by Django 4.2.6 on 2023-10-31 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_date_owner_alter_entry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='end_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='medium', max_length=10),
        ),
    ]
