# Generated by Django 4.2.6 on 2023-11-07 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_entry_end_time_entry_start_time_alter_entry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
